version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    volumes:
      - mariadb_volume:/var/lib/mysql
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    image: nginx
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    depends_on:        		
      - wordpress
    ports:
      - "443:443"

  wordpress:
    container_name: wordpress
    image: wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    env_file: .env
    restart: on-failure
    expose: 
      - "9000"
    depends_on:
      - mariadb

networks:
  inception:
    driver: bridge

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/diroyer/data/DB/
      o: bind
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      device: /home/diroyer/data/WordPress/
      o: bind
